; generated by Slic3r Prusa Edition 1.42.0-alpha4+linux64 on 2019-02-03 at 09:45:52

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R1
M73 Q0 S1
M201 X1000 Y1000 Z1000 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E1.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M115 U3.4.1 ; tell printer latest fw version
M83  ; extruder relative mode
M104 S201 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S201 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0  F1000.0 ; intro line
M73 Q5 S1
M73 P5 R1
G1 X100.0 E12.5  F1000.0 ; intro line
G92 E0.0
M221 S95
M900 K30; Filament gcode
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 E-0.80000 F2100.00000
G1 Z0.600 F10800.000
;AFTER_LAYER_CHANGE
;0.2
G1 X3.615 Y5.053
G1 Z0.200
G1 E0.80000 F2100.00000
M204 S1000
G1 F1200
G1 X4.079 Y4.299 E0.02778
G1 X4.460 Y3.948 E0.01623
G1 X4.899 Y3.682 E0.01610
G1 X5.387 Y3.509 E0.01623
G1 X5.899 Y3.436 E0.01623
G1 X26.004 Y3.434 E0.63036
G1 X26.936 Y3.611 E0.02973
G1 X27.742 Y4.117 E0.02985
G1 X28.309 Y4.882 E0.02985
G1 X28.558 Y5.797 E0.02973
G1 X28.565 Y26.075 E0.63582
G1 X28.385 Y26.947 E0.02790
G1 X27.921 Y27.701 E0.02778
G1 X27.527 Y28.061 E0.01672
G1 X27.065 Y28.334 E0.01684
G1 X26.559 Y28.504 E0.01672
G1 X26.025 Y28.566 E0.01684
G1 X5.925 Y28.565 E0.63024
G1 X5.053 Y28.385 E0.02790
G1 X4.299 Y27.921 E0.02778
G1 X3.939 Y27.527 E0.01672
G1 X3.666 Y27.065 E0.01684
G1 X3.496 Y26.559 E0.01672
G1 X3.434 Y26.025 E0.01684
G1 X3.435 Y5.925 E0.63024
G1 X3.603 Y5.112 E0.02602
G1 F8640
G1 X4.079 Y4.299 E-0.21763
G1 X4.460 Y3.948 E-0.11949
G1 X4.899 Y3.682 E-0.11859
G1 X5.387 Y3.509 E-0.11949
G1 X5.899 Y3.436 E-0.11949
G1 X6.182 Y3.436 E-0.06530
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X5.077 Y4.015
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200
G1 X5.925 Y3.813 E0.02732
G1 X26.004 Y3.811 E0.62956
G1 X26.803 Y3.964 E0.02552
G1 X27.494 Y4.401 E0.02563
G1 X27.977 Y5.061 E0.02563
G1 X28.183 Y5.848 E0.02552
G1 X28.188 Y26.058 E0.63368
G1 X28.032 Y26.813 E0.02417
G1 X27.626 Y27.465 E0.02405
G1 X26.899 Y27.995 E0.02822
G1 X26.017 Y28.189 E0.02833
G1 X5.942 Y28.188 E0.62945
G1 X5.187 Y28.032 E0.02417
G1 X4.535 Y27.626 E0.02405
G1 X4.005 Y26.899 E0.02822
G1 X3.811 Y26.017 E0.02833
G1 X3.812 Y5.942 E0.62945
G1 X3.968 Y5.187 E0.02417
G1 X4.374 Y4.535 E0.02405
G1 X5.029 Y4.051 E0.02555
G1 F8640
G1 X5.925 Y3.813 E-0.21401
G1 X8.289 Y3.813 E-0.54599
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X12.558 Y12.950
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200
G1 X14.369 Y11.700 E0.06902
G1 X16.554 Y11.435 E0.06902
G1 X18.613 Y12.215 E0.06902
G1 X20.072 Y13.863 E0.06902
G1 X20.599 Y16.000 E0.06902
G1 X20.072 Y18.137 E0.06902
G1 X18.613 Y19.785 E0.06902
G1 X16.554 Y20.565 E0.06902
G1 X14.369 Y20.300 E0.06902
G1 X12.558 Y19.050 E0.06902
G1 X11.535 Y17.101 E0.06902
G1 X11.535 Y14.899 E0.06902
G1 X12.530 Y13.003 E0.06714
G1 X12.848 Y13.208 F10800.000
G1 F1200
G1 X14.507 Y12.063 E0.06319
G1 X16.508 Y11.820 E0.06319
G1 X18.392 Y12.535 E0.06319
G1 X19.728 Y14.043 E0.06319
G1 X20.211 Y16.000 E0.06319
G1 X19.728 Y17.957 E0.06319
G1 X18.392 Y19.465 E0.06319
G1 X16.508 Y20.180 E0.06319
G1 X14.507 Y19.937 E0.06319
G1 X12.848 Y18.792 E0.06319
G1 X11.912 Y17.008 E0.06319
G1 X11.912 Y14.992 E0.06319
G1 X12.820 Y13.261 E0.06131
G1 X12.722 Y12.828 F10800.000
G1 F8640
G1 X14.507 Y12.063 E-0.47765
G1 X15.721 Y11.916 E-0.28235
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X6.587 Y6.587
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200
G1 X25.413 Y6.587 E0.59027
G1 X25.413 Y25.413 E0.59027
G1 X6.587 Y25.413 E0.59027
G1 X6.587 Y6.647 E0.58839
G1 X6.210 Y6.210 F10800.000
G1 F1200
G1 X25.790 Y6.210 E0.61392
G1 X25.790 Y25.790 E0.61392
G1 X6.210 Y25.790 E0.61392
G1 X6.210 Y6.270 E0.61204
G1 X6.596 Y6.313 F10800.000
G1 F8640
G1 X9.501 Y6.260 E-0.76000
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X11.875 Y18.358
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200
G1 X6.870 Y13.352 E0.22483
G1 X6.870 Y12.812 E0.01716
G1 X11.278 Y17.221 E0.19803
G1 X11.252 Y17.170 E0.00181
G1 X11.252 Y16.654 E0.01640
G1 X6.870 Y12.272 E0.19684
G1 X6.870 Y11.732 E0.01716
G1 X11.252 Y16.114 E0.19684
G1 X11.252 Y15.574 E0.01716
G1 X6.870 Y11.192 E0.19684
G1 X6.870 Y10.651 E0.01716
G1 X11.252 Y15.033 E0.19684
G1 X11.252 Y14.830 E0.00647
G1 X11.368 Y14.609 E0.00792
G1 X6.870 Y10.111 E0.20204
G1 X6.870 Y9.571 E0.01716
G1 X11.554 Y14.255 E0.21039
G1 X11.740 Y13.900 E0.01271
G1 X6.870 Y9.031 E0.21874
G1 X6.870 Y8.491 E0.01716
G1 X11.926 Y13.546 E0.22710
G1 X12.111 Y13.192 E0.01271
G1 X6.870 Y7.950 E0.23545
G1 X6.870 Y7.410 E0.01716
G1 X12.297 Y12.838 E0.24380
G1 X12.340 Y12.757 E0.00289
G1 X12.587 Y12.587 E0.00953
G1 X6.870 Y6.870 E0.25679
G1 X7.410 Y6.870 E0.01716
G1 X12.906 Y12.366 E0.24689
G1 X13.226 Y12.145 E0.01233
G1 X7.950 Y6.870 E0.23698
G1 X8.490 Y6.870 E0.01716
G1 X13.545 Y11.925 E0.22707
G1 X13.865 Y11.704 E0.01233
G1 X9.031 Y6.870 E0.21716
G1 X9.571 Y6.870 E0.01716
G1 X14.185 Y11.484 E0.20725
G1 X14.266 Y11.428 E0.00314
G1 X14.625 Y11.384 E0.01150
G1 X10.111 Y6.870 E0.20277
G1 X10.651 Y6.870 E0.01716
G1 X15.107 Y11.325 E0.20014
G1 X15.589 Y11.267 E0.01541
G1 X11.191 Y6.870 E0.19751
G1 X11.732 Y6.870 E0.01716
G1 X16.070 Y11.208 E0.19489
G1 X16.552 Y11.150 E0.01541
G1 X12.272 Y6.870 E0.19226
G1 X12.812 Y6.870 E0.01716
G1 X17.392 Y11.450 E0.20573
G1 X18.262 Y11.780 E0.02956
G1 X13.352 Y6.870 E0.22056
G1 X13.893 Y6.870 E0.01716
G1 X25.130 Y18.107 E0.50478
G1 X25.130 Y17.567 E0.01716
G1 X14.433 Y6.870 E0.48052
G1 X14.973 Y6.870 E0.01716
G1 X25.130 Y17.027 E0.45625
G1 X25.130 Y16.487 E0.01716
G1 X15.513 Y6.870 E0.43198
G1 X16.053 Y6.870 E0.01716
G1 X25.130 Y15.947 E0.40772
G1 X25.130 Y15.406 E0.01716
G1 X16.594 Y6.870 E0.38345
G1 X17.134 Y6.870 E0.01716
G1 X25.130 Y14.866 E0.35919
G1 X25.130 Y14.326 E0.01716
G1 X17.674 Y6.870 E0.33492
G1 X18.214 Y6.870 E0.01716
G1 X25.130 Y13.786 E0.31065
G1 X25.130 Y13.246 E0.01716
G1 X18.754 Y6.870 E0.28639
G1 X19.295 Y6.870 E0.01716
G1 X25.130 Y12.705 E0.26212
G1 X25.130 Y12.165 E0.01716
G1 X19.835 Y6.870 E0.23786
G1 X20.375 Y6.870 E0.01716
G1 X25.130 Y11.625 E0.21359
G1 X25.130 Y11.085 E0.01716
G1 X20.915 Y6.870 E0.18933
G1 X21.456 Y6.870 E0.01716
G1 X25.130 Y10.544 E0.16506
G1 X25.130 Y10.004 E0.01716
G1 X21.996 Y6.870 E0.14079
G1 X22.536 Y6.870 E0.01716
G1 X25.130 Y9.464 E0.11653
G1 X25.130 Y8.924 E0.01716
G1 X23.076 Y6.870 E0.09226
G1 X23.616 Y6.870 E0.01716
G1 X25.130 Y8.384 E0.06800
G1 X25.130 Y7.843 E0.01716
G1 X24.157 Y6.870 E0.04373
G1 X24.697 Y6.870 E0.01716
G1 X25.300 Y7.473 E0.02709
G1 F8640
G1 X24.697 Y6.870 E-0.19691
G1 X24.157 Y6.870 E-0.12474
G1 X25.130 Y7.843 E-0.31790
G1 X25.130 Y8.365 E-0.12045
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X25.300 Y18.817
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200
G1 X20.369 Y13.887 E0.22147
G1 X20.546 Y14.604 E0.02345
G1 X25.130 Y19.188 E0.20591
G1 X25.130 Y19.728 E0.01716
G1 X20.723 Y15.321 E0.19798
G1 X20.885 Y16.023 E0.02288
G1 X25.130 Y20.268 E0.19071
G1 X25.130 Y20.809 E0.01716
G1 X20.778 Y16.456 E0.19550
G1 X20.671 Y16.890 E0.01418
G1 X25.130 Y21.349 E0.20030
G1 X25.130 Y21.889 E0.01716
G1 X20.564 Y17.323 E0.20510
G1 X20.457 Y17.756 E0.01418
G1 X25.130 Y22.429 E0.20990
G1 X25.130 Y22.969 E0.01716
G1 X20.350 Y18.190 E0.21470
G1 X20.330 Y18.273 E0.00271
G1 X20.125 Y18.504 E0.00983
G1 X25.130 Y23.510 E0.22483
G1 X25.130 Y24.050 E0.01716
G1 X19.871 Y18.791 E0.23623
G1 X19.617 Y19.077 E0.01216
G1 X25.130 Y24.590 E0.24763
G1 X25.130 Y25.130 E0.01716
G1 X19.364 Y19.364 E0.25903
G1 X19.110 Y19.650 E0.01216
G1 X24.590 Y25.130 E0.24616
G1 X24.050 Y25.130 E0.01716
G1 X18.856 Y19.936 E0.23330
G1 X18.778 Y20.025 E0.00374
G1 X18.507 Y20.127 E0.00921
G1 X23.509 Y25.130 E0.22472
G1 X22.969 Y25.130 E0.01716
G1 X18.115 Y20.276 E0.21805
G1 X17.723 Y20.425 E0.01331
G1 X22.429 Y25.130 E0.21137
G1 X21.889 Y25.130 E0.01716
G1 X17.332 Y20.573 E0.20470
G1 X16.940 Y20.722 E0.01331
G1 X21.349 Y25.130 E0.19803
G1 X20.808 Y25.130 E0.01716
G1 X16.525 Y20.847 E0.19241
G1 X15.910 Y20.772 E0.01967
G1 X20.268 Y25.130 E0.19576
G1 X19.728 Y25.130 E0.01716
G1 X15.295 Y20.697 E0.19912
G1 X14.680 Y20.623 E0.01967
G1 X19.188 Y25.130 E0.20247
G1 X18.648 Y25.130 E0.01716
G1 X13.697 Y20.180 E0.22236
G1 F8640
G1 X16.025 Y22.507 E-0.76000
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
G1 X18.277 Y25.300
G1 Z0.200
G1 E0.80000 F2100.00000
G1 F1200
G1 X6.870 Y13.893 E0.51240
G1 X6.870 Y14.433 E0.01716
G1 X17.567 Y25.130 E0.48051
G1 X17.027 Y25.130 E0.01716
G1 X6.870 Y14.973 E0.45624
G1 X6.870 Y15.513 E0.01716
G1 X16.487 Y25.130 E0.43198
G1 X15.946 Y25.130 E0.01716
G1 X6.870 Y16.054 E0.40771
G1 X6.870 Y16.594 E0.01716
G1 X15.406 Y25.130 E0.38345
G1 X14.866 Y25.130 E0.01716
G1 X6.870 Y17.134 E0.35918
G1 X6.870 Y17.674 E0.01716
G1 X14.326 Y25.130 E0.33492
M73 Q88 S0
G1 X13.786 Y25.130 E0.01716
G1 X6.870 Y18.214 E0.31065
M73 P89 R0
G1 X6.870 Y18.755 E0.01716
G1 X13.245 Y25.130 E0.28638
G1 X12.705 Y25.130 E0.01716
G1 X6.870 Y19.295 E0.26212
G1 X6.870 Y19.835 E0.01716
G1 X12.165 Y25.130 E0.23785
G1 X11.625 Y25.130 E0.01716
G1 X6.870 Y20.375 E0.21359
G1 X6.870 Y20.915 E0.01716
G1 X11.085 Y25.130 E0.18932
G1 X10.544 Y25.130 E0.01716
G1 X6.870 Y21.456 E0.16505
G1 X6.870 Y21.996 E0.01716
G1 X10.004 Y25.130 E0.14079
G1 X9.464 Y25.130 E0.01716
G1 X6.870 Y22.536 E0.11652
G1 X6.870 Y23.076 E0.01716
G1 X8.924 Y25.130 E0.09226
G1 X8.383 Y25.130 E0.01716
G1 X6.870 Y23.617 E0.06799
G1 X6.870 Y24.157 E0.01716
G1 X7.843 Y25.130 E0.04373
G1 X7.303 Y25.130 E0.01716
G1 X6.700 Y24.527 E0.02708
G1 F8640;_WIPE
G1 X7.303 Y25.130 E-0.19687
G1 F8640;_WIPE
G1 X7.843 Y25.130 E-0.12474
G1 F8640;_WIPE
G1 X6.870 Y24.157 E-0.31787
G1 F8640;_WIPE
G1 X6.870 Y23.635 E-0.12052
G1 E-0.04000 F2100.00000
G1 Z0.800 F10800.000
; Filament-specific end gcode
G4 ; wait
M221 S100
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.8 ; Move print head up
G1 X0 Y200; home X axis
M84 ; disable motors
; filament used = 35.7mm (0.1cm3)
; filament used = 0.1
; filament cost = 0.0
; total filament cost = 0.0
; estimated printing time (normal mode) = 1m 11s
; estimated printing time (silent mode) = 1m 12s

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,250x0,250x210,0x210
; bed_size_x = 68
; bed_size_y = 120
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bridge_acceleration = 1000
; bridge_fan_speed = 100
; brim_width = 0
; colorprint_heights = 
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; deretract_speed = 0
; disable_fan_first_layers = 1
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200; home X axis\nM84 ; disable motors
; exp_time = 8
; exp_time_first = 35
; extra_loading_move = -2
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FFFF00
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF3232
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 24.99
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_speed = 20
; first_layer_temperature = 201
; gcode_comments = 0
; gcode_flavor = marlin
; high_current_on_filament_swap = 0
; infill_acceleration = 1250
; infill_first = 0
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 1000,1000
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 1.5,1.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_fan_speed = 100
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}.gcode
; parking_pos_retraction = 92
; perimeter_acceleration = 800
; pixel_height = 2560
; pixel_width = 1440
; post_process = 
; printer_model = MK3
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.6
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slowdown_below_layer_time = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{else}30{endif}; Filament gcode"
; start_gcode = M115 U3.4.1 ; tell printer latest fw version\nM83  ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0  F1000.0 ; intro line\nG1 X100.0 E12.5  F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height==0.05}100{else}95{endif}
; temperature = 220
; threads = 2
; toolchange_gcode = 
; travel_speed = 180
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; z_offset = 0
; clip_multipart_objects = 1
; dont_support_bridges = 1
; elefant_foot_compensation = 0
; extrusion_width = 0.45
; first_layer_height = 0.2
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.15
; raft_layers = 0
; seam_position = nearest
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 50%
; wipe_into_objects = 0
; xy_size_compensation = 0
; bottom_solid_layers = 5
; bridge_angle = 0
; bridge_flow_ratio = 0.8
; bridge_speed = 30
; ensure_vertical_shell_thickness = 1
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_perimeters = 0
; fill_angle = 45
; fill_density = 20%
; fill_pattern = grid
; gap_fill_speed = 40
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_overlap = 25%
; infill_speed = 200
; overhangs = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 45
; perimeters = 2
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 200
; thin_walls = 0
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 50
; top_solid_layers = 7
; wipe_into_infill = 0
; print_settings_id = 0.15mm OPTIMAL MK3
; filament_settings_id = "Prusament PLA"
; printer_settings_id = Original Prusa i3 MK3
; printer_model = MK3
; printer_variant = 0.4
; default_print_profile = 0.15mm OPTIMAL MK3
; default_filament_profile = "Prusament PLA"
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
